name: Build

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main
      - '*'

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

defaults:
    run:
        shell: bash {0}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Requirements
      run: |
        sudo apt-get install mingw-w64 markdown libfuse-dev

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Linux
      run: |
        sudo make -C build/unix unixpackage
      
    - name: Build Windows
      run: |
        sudo make -C build/unix winpackage

    - name: Results
      run: |
        [ -f build/unix/toolshed-*.tgz ] && ls build/unix/toolshed-*.tgz | xargs -I {} bash -c 'echo; md5sum {}; ls -al --color=auto {}; tar tzvf {}'
        [ -f build/unix/toolshed-*.zip ] && ls build/unix/toolshed-*.zip | xargs -I {} bash -c 'echo; md5sum {}; ls -al --color=auto {}; unzip -l -v {}'

